### ISSUE TITLE
no "gpt-3.5-turbo" support

### ISSUE THREAD

**Issue by jembem** [landgraf-dev/openai-delphi#6]
please add "gpt-3.5-turbo" support which was introduced few days ago.

**Comment by CardanoDVPR** [comment]
Yes. Trying to use this with gpt-3.5-turbo. The completions is different /v1/chat/completions, but there seem to be some parameter changes as well.

**Comment by HemulGM** [comment]
> please add "gpt-3.5-turbo" support which was introduced few days ago.

You can use https://github.com/HemulGM/DelphiOpenAI

**Comment by CardanoDVPR** [comment]
I notice this statement. "Althought not fully tested, it should also work on all supported platforms (Windows, Linux, macOS, Android, iOS)."  

I think this means you can compile in Delphi to run on those platforms. I develop in Linux using Lazarus, since Delphi cannot run on Lazarus. This project has allowed me to use the OpenAIClient.pas library in Lazarus on Linux. 

If I am incorrect please let me know. From what I saw of the the DelphiOpenAI, it uses fmx which is not compatible with Lazarus on any platform.

**Comment by HemulGM** [comment]
It does not use FMX, but yes, the code, although cross-platform, is not compatible with FPC

**Comment by wlandgraf** [comment]
This repository is fully FPC compatible. Would you mind not hijacking this issue/repo and discuss it in the proper location? Thank you.

**Comment by jembem** [comment]
still no support for GPT-3.5-Turbo

**Comment by CardanoDVPR** [comment]
Is this project dead? There have been no updates for several months now.

**Comment by wlandgraf** [comment]
No, it's not.

**Comment by wlandgraf** [comment]
Project has now been updated and supports the new chat completion endpoint, which in turn support the newest models, including of course GPT-3.5-Turbo.

The demos for Delphi and Lazarus were also updated, so you can test and play with it right away.

**Comment by CardanoDVPR** [comment]
Thank you!
